language: go
go:
- 1.10.x
script: go test -v && go build
before_deploy: "./create_binaries.sh && ls -la /var/tmp/ctwrapper"
deploy:
  provider: releases
  api_key:
    secure: "fZbSdQikiD97nIHS6BYEB0kNJ7/VcWNOm8Mku4TmQOKYtuI7rHkxGrZkGoX4XfGexlM/ZhawaYkc1IAFoUQSsh2ulywz4ghJ6057X9ajyzasFYhLWmLy/FewQfFubjK+FIwgUlCQvBy6AfoEU2knhLFTPAAK8UT++IqE2boG66LF8fDAwMp/OVtBH0w3mcv0mPR1XL43Nsyf+h6OCQ4ElYM81q9EYaYJTX6nodQFtWJpVrZzZzsIFZevcFFs2AWITmhD7RQ3Pz1NnyaGFw9j7nAnltlhsD84nbnnKxAlILidB1WZW1uYsXCPjRZk81C/6kk0BTAHCCG20siNt6yCIp7b2uPADEoTitdp4/3fMQbjiOvocTueB1C/Y5fezmwJz/W9bKTi0XluvuP8tN9ohvWbKIqlpcNMczZSDavZV+3EcpB2BnUb1w1XgWkINm23DpcFp12P7TSXK7uAS9mllHkCTMU5XEddnpQ06TnWoIewhZovo6wSmU6X8OA93NXIE49XynXlCjkrZGtGHMFZ8Mm/XubOtnQiJaik/g5P449vqpd6BwoV4AZuJwEIL6tDlgfsaDUl5DPTgo/eZZubHnM2ntvkc/UaklUppis6wrf9JhlfQ5iBCQvpsMn6AXrv0G7rd+AE970zz/vIkV9IRi9C4+mWP5/X7ANT9UaVz8Y="
  file_glob: true
  file: /var/tmp/ctwrapper/*
  skip_cleanup: true
  on:
    repo: nxadm/ctwrapper
    tags: true
    branches:
      only:
      - /^v\d+\.\d+\.\d+$/    
