language: go
go:
- 1.10.x
script: go test -v && go build
before_deploy: "./create_binaries.sh && ls -la /var/tmp/ctwrapper"
deploy:
  provider: releases
  api_key:
    secure: kk8l25NJe0B5tIRSMsev1T0PMQbfnVswYq3x/LbAirqWFy5lsFp0T6q4INchnEigmvCsFna38BObOvreGvmxRqb+4a67O5V+ZY2geYw3+YSFOl30FFPp073re/vY5phVFwgV5q1UaSndQ7rXvRHcfqRFzVXs/wQM959NmNqzID6UupglXlU0gqrGBN5JJfUxoDclj/I2TAGAWF2qeuCr6rY4ukpWAlJcTl8E69BwI+/st7ZeAeeEqg17uQ1qEZpE0EwKHmHBHhsuEDO4DXGh3GvqIkaPE50k6TJD0JsEpfM5HLXZGoT/P4CvubKCdVbDACimxl7mNv6aLvjiwU9n2aXipo7GWGFh/QZXTaeH190wCAk408L6Pqa/4vtFnPsNCpJpEoNVEdaYpV/tUtzm3eJw0rUDZiJnEisCNq4BtIeybyIEyB8Dr7l0aARTT8nuRDiJ6Qjan9MyvInrlg7A+F+VXsFkz2erF7CkXE8keQ8ZebDKxCqFbFXsesh9KIqxSKYa/myhUHekTbXzRsoTNFpJlk6QuGdCHFaG7OiXXLjMajdBC5bksxLoDBBFY7nd09D1Lt4ClzjM56Xkn7kIQF6D8nYbY8wFb8kQixvqS5RxxGmX06bvq4H9s2yhcvdLrTxOeKMBF28QCRTaHnZUolgmRPV96otLg042vY7rHh0=
  file_glob: true
  file: /var/tmp/ctwrapper/*
  skip_cleanup: true
  on:
    repo: nxadm/ctwrapper
    tags: true
    branches:
      only:
      - /^v\d+\.\d+\.\d+$/    
