language: go
go:
- 1.10.x
script: go test -v && go build
before_deploy: "./create_binaries.sh && ls -la /var/tmp/ctwrapper"
deploy:
  provider: releases
  api_key:
    secure: F5BRaXo6FceeLGZe6hZ9HTbW2JOmqEihZt2nIGpbdjLchAGTjoR72t78vzhgi2vXQ79UN16pwjefefTqveHjQTunYttNzjvH0Mvv1Xzxv6tDdpHOdgL7/OwOmr7iyUJyZJqM9nUF1+VJ2bqOnAxtLYT6kkm6PoihgjDIDbEdFyY2PkAzCzxED+Vp0ADPRMA4tpDxzYAH3CNkc4oPrmNdxnYC5a42MD24PtLIYv+j2Bm3h+vYfsz9We0UXsubFxQO9YVz/VZQE0oecayiaxuSeGUDNQayIK4hKuoKWrBndNGCzmdZzLqsrGMIn6EzQy10g0968ng5lnowo/1KB4CBTxwLNPd0fMMPorjiDlrONnaf1m2E7By/RGts6GfxH+puKm4em/qsm9MkYxuxH6o/aEKoLlpD1GIUVSj78JJ346kF8CVoHCwZl1gblppIHgfCsGJ87mlAmef0PqvHFWG4khW11sSAA0f6czPDxAqbkV5CjRLd8dF4VT0a/BD8YlSXbDyBfv7Ta+lIWzkgV3rHDuye0yfUYwrPBgTVgr09VulFaoJSF4CLJi1SZS2hPKCAtjiVupwVL+1pgxOaXNRHpwjBTGYh+CBoyyTKyJR6ifDamk2KjZDYgzzOfxjdTj3A6dhZpaLA1ssYJWu5l72EGuBTq0bJqqBasEr0nkrCVwg=
  file_glob: true
  file: /var/tmp/ctwrapper/*
  skip_cleanup: true
  on:
    repo: nxadm/ctwrapper
    tags: true
    branches:
      only:
      - /^v\d+\.\d+\.\d+$/    
